name: ecofinds
description: A sustainable second-hand marketplace app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.10
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^5.1.1
  permission_handler: ^11.0.1
  smooth_page_indicator: ^1.1.0
  confetti: ^0.7.0
  flutter_localizations:
    sdk: flutter
  geolocator: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/placeholder.png

